/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mendaftarkan user baru (Customer/Driver) */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login dan dapatkan JWT access token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (menghapus session cookie) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dapatkan profil user saat ini (semua role yang sudah login) */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set driver online dengan lokasi awal */
        post: operations["DriverController_setOnline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set driver offline */
        post: operations["DriverController_setOffline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mendapatkan daftar pesanan milik user saat ini */
        get: operations["OrderController_getOrders"];
        put?: never;
        /** Membuat pesanan baru (Hanya Customer) */
        post: operations["OrderController_createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimasi pesanan (jarak, waktu, biaya) */
        post: operations["OrderController_estimateOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mendapatkan detail pesanan */
        get: operations["OrderController_getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mengubah status pesanan (Hanya Driver yang di-assign) */
        patch: operations["OrderController_updateStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description Email unik pengguna
             * @example johndoe@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
            /** @example Budi Santoso */
            name: string;
            /**
             * @description CUSTOMER atau DRIVER
             * @example CUSTOMER
             * @enum {string}
             */
            role: "CUSTOMER" | "DRIVER";
        };
        UserResponseDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example customer@example.com */
            email: string;
            /** @example Budi Santoso */
            name: string;
            /**
             * @example CUSTOMER
             * @enum {string}
             */
            role: "CUSTOMER" | "DRIVER";
        };
        ErrorResponseDto: {
            /** @example 400 */
            statusCode: number;
            /** @example VALIDATION_ERROR */
            code: string;
            message: string | string[];
        };
        LoginDto: {
            /**
             * @description Email unik pengguna
             * @example johndoe@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        TokenResponseDto: {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI... */
            accessToken: string;
        };
        DriverLocationDto: {
            /**
             * @description Latitude
             * @example -6.9147
             */
            lat: number;
            /**
             * @description Longitude
             * @example 107.6098
             */
            lng: number;
        };
        SuccessResponseDto: {
            /** @example true */
            ok: boolean;
        };
        CoordinateDto: {
            /** @example -6.9147 */
            lat: number;
            /** @example 107.6098 */
            lng: number;
        };
        CreateOrderDto: {
            pickup: components["schemas"]["CoordinateDto"];
            dropoff: components["schemas"]["CoordinateDto"];
        };
        RouteGeometryDto: {
            /** @example LineString */
            type: string;
            /**
             * @example [
             *       [
             *         107.6098,
             *         -6.9147
             *       ],
             *       [
             *         107.6186,
             *         -6.9034
             *       ]
             *     ]
             */
            coordinates: string[];
        };
        OrderDto: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            id: string;
            /** @example 123e4567-e89b-12d3-a456-426614174001 */
            customerId: string;
            /** @example 123e4567-e89b-12d3-a456-426614174002 */
            driverId?: string;
            /**
             * @example DRIVER_ASSIGNED
             * @enum {string}
             */
            status: "PENDING" | "DRIVER_ASSIGNED" | "PICKED_UP" | "COMPLETED" | "NO_DRIVER_AVAILABLE";
            pickup: components["schemas"]["CoordinateDto"];
            dropoff: components["schemas"]["CoordinateDto"];
            /** @example 1650 */
            distanceM: number;
            /** @example 10000 */
            fee: number;
            /** @example 312 */
            durationS?: number;
            /**
             * @example STRAIGHT_LINE
             * @enum {string}
             */
            routeSource: "OSRM" | "STRAIGHT_LINE";
            route?: components["schemas"]["RouteGeometryDto"];
            /**
             * Format: date-time
             * @example 2026-10-01T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-10-01T12:05:00Z
             */
            updatedAt: string;
        };
        EstimateOrderDto: {
            pickup: components["schemas"]["CoordinateDto"];
            dropoff: components["schemas"]["CoordinateDto"];
        };
        OrderEstimateDto: {
            /** @example 2105 */
            distanceM: number;
            /** @example 312 */
            durationS?: number;
            /** @example 10500 */
            fee: number;
            /**
             * @example OSRM
             * @enum {string}
             */
            routeSource: "OSRM" | "STRAIGHT_LINE";
            route?: components["schemas"]["RouteGeometryDto"];
        };
        UpdateOrderStatusDto: {
            /**
             * @example PICKED_UP
             * @enum {string}
             */
            status: "PICKED_UP" | "COMPLETED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User berhasil didaftarkan */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Validasi gagal (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Email sudah terdaftar (EMAIL_TAKEN) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Berhasil login */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description Validasi gagal (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Kredensial tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Berhasil logout */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil berhasil diambil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Token tidak ada atau tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Auth service tidak tersedia (SERVICE_UNAVAILABLE) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DriverController_setOnline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverLocationDto"];
            };
        };
        responses: {
            /** @description Driver berhasil online */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
            /** @description Validasi gagal (VALIDATION_ERROR) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Token tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Bukan role DRIVER (FORBIDDEN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DriverController_setOffline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Driver berhasil offline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponseDto"];
                };
            };
            /** @description Token tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Bukan role DRIVER (FORBIDDEN) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrderController_getOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pesanan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"][];
                };
            };
            /** @description Token tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Layanan order tidak tersedia (SERVICE_UNAVAILABLE) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrderController_createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            /** @description Pesanan berhasil dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description Payload tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Token tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Hanya customer yang bisa pesan */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Layanan order tidak tersedia (SERVICE_UNAVAILABLE) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrderController_estimateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EstimateOrderDto"];
            };
        };
        responses: {
            /** @description Estimasi berhasil dihitung */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderEstimateDto"];
                };
            };
            /** @description Payload tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Token tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrderController_getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail pesanan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description Token tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Akses ditolak */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Pesanan tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Layanan order tidak tersedia (SERVICE_UNAVAILABLE) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    OrderController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusDto"];
            };
        };
        responses: {
            /** @description Status berhasil diubah */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDto"];
                };
            };
            /** @description Payload tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Token tidak valid (UNAUTHORIZED) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Hanya driver yang di-assign */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Pesanan tidak ditemukan */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Transisi status ilegal */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Layanan order tidak tersedia (SERVICE_UNAVAILABLE) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
