services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: oddt-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    container_name: oddt-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped

volumes:
  pgdata:
