// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.4
//   protoc               v3.19.1
// source: location.proto

/* eslint-disable */
import type { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export interface FindNearestDriversRequest {
  lat: number;
  lng: number;
  radiusM: number;
  limit: number;
}

export interface NearbyDriver {
  driverId: string;
  distanceM: number;
  lat: number;
  lng: number;
}

export interface FindNearestDriversResponse {
  drivers: NearbyDriver[];
}

export interface SetDriverAvailabilityRequest {
  driverId: string;
  isAvailable: boolean;
  lat: number;
  lng: number;
}

export interface SetDriverAvailabilityResponse {
  ok: boolean;
}

export interface LocationServiceClient {
  findNearestDrivers(
    request: FindNearestDriversRequest,
    metadata: Metadata,
    ...rest: any
  ): Observable<FindNearestDriversResponse>;

  setDriverAvailability(
    request: SetDriverAvailabilityRequest,
    metadata: Metadata,
    ...rest: any
  ): Observable<SetDriverAvailabilityResponse>;
}

export interface LocationServiceController {
  findNearestDrivers(
    request: FindNearestDriversRequest,
    metadata: Metadata,
    ...rest: any
  ):
    | Promise<FindNearestDriversResponse>
    | Observable<FindNearestDriversResponse>
    | FindNearestDriversResponse;

  setDriverAvailability(
    request: SetDriverAvailabilityRequest,
    metadata: Metadata,
    ...rest: any
  ):
    | Promise<SetDriverAvailabilityResponse>
    | Observable<SetDriverAvailabilityResponse>
    | SetDriverAvailabilityResponse;
}

export function LocationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'findNearestDrivers',
      'setDriverAvailability',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('LocationService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('LocationService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
      Object.defineProperty(constructor.prototype, method, descriptor);
    }
  };
}

export const LOCATION_SERVICE_NAME = 'LocationService';
